environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  SDL2_VERSION: 2.0.12
  SDL2_MIXER_VERSION: 2.0.4
  MINGW_PATH: C:\MinGW
  MINGW_W64_PATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1
  SDLDIR: C:\MinGW
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      COMPILER: mingw
      CMAKE_BUILD_TYPE: Release
      PLATFORMTOOLSET: "v140"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      COMPILER: mingw-w64
      PLATFORMTOOLSET: "v140"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      COMPILER: msvc

platform:
  - x86

install:
  - IF NOT EXIST SDL2-devel-%SDL2_VERSION%-mingw.tar.gz appveyor DownloadFile http://libsdl.org/release/SDL2-devel-%SDL2_VERSION%-mingw.tar.gz
  - IF NOT EXIST SDL2_mixer-devel-%SDL2_MIXER_VERSION%-mingw.tar.gz appveyor DownloadFile https://libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-%SDL2_MIXER_VERSION%-mingw.tar.gz
  - IF NOT EXIST SDL2-devel-%SDL2_VERSION%-VC.zip appveyor DownloadFile http://libsdl.org/release/SDL2-devel-%SDL2_VERSION%-VC.zip
  - IF NOT EXIST SDL2_mixer-devel-%SDL2_MIXER_VERSION%-VC.zip appveyor DownloadFile https://libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-%SDL2_MIXER_VERSION%-VC.zip
  - if [%COMPILER%] == [mingw] 7z x SDL2-devel-%SDL2_VERSION%-mingw.tar.gz -so | 7z x -si -ttar -oC:\
  - if [%COMPILER%] == [mingw] echo y | xcopy C:\SDL2-%SDL2_VERSION%\i686-w64-mingw32\* %MINGW_PATH%\ /S
  - if [%COMPILER%] == [mingw] 7z x SDL2_mixer-devel-%SDL2_MIXER_VERSION%-mingw.tar.gz -so | 7z x -si -ttar -oC:\
  - if [%COMPILER%] == [mingw] echo y | xcopy C:\SDL2_mixer-%SDL2_MIXER_VERSION%\i686-w64-mingw32\* %MINGW_PATH%\ /S
  - if [%COMPILER%] == [mingw-w64] 7z x SDL2-devel-%SDL2_VERSION%-mingw.tar.gz -so | 7z x -si -ttar -oC:\
  - if [%COMPILER%] == [mingw-w64] echo y | xcopy C:\SDL2-%SDL2_VERSION%\x86_64-w64-mingw32\* %MINGW_W64_PATH%\mingw64\ /S
  - if [%COMPILER%] == [mingw-w64] 7z x SDL2_mixer-devel-%SDL2_MIXER_VERSION%-mingw.tar.gz -so | 7z x -si -ttar -oC:\
  - if [%COMPILER%] == [mingw-w64] echo y | xcopy C:\SDL2_mixer-%SDL2_MIXER_VERSION%\x86_64-w64-mingw32\* %MINGW_W64_PATH%\mingw64\ /S
  - if [%COMPILER%] == [msvc] md C:\sdl-msvc
  - if [%COMPILER%] == [msvc] 7z x SDL2-devel-%SDL2_VERSION%-VC.zip -oC:\sdl-msvc
  - if [%COMPILER%] == [msvc] 7z x SDL2_mixer-devel-%SDL2_MIXER_VERSION%-VC.zip -oC:\sdl-msvc

before_build:
  - if [%COMPILER%] == [mingw] set Path=%MINGW_PATH%\bin;%Path%
  - if [%COMPILER%] == [mingw-w64] set Path=%MINGW_W64_PATH%\mingw64\bin;%Path%
  - md build
  - cd build
  - if [%COMPILER%] == [mingw] cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DSYSTEM_LIBS=OFF -D CMAKE_C_COMPILER=mingw32-gcc.exe -D CMAKE_MAKE_PROGRAM=mingw32-make.exe ..
  - if [%COMPILER%] == [mingw-w64] cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DSYSTEM_LIBS=OFF -D CMAKE_C_COMPILER=x86_64-w64-mingw32-gcc.exe -D CMAKE_MAKE_PROGRAM=mingw32-make.exe ..
  - if [%COMPILER%] == [msvc] cmake -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DSYSTEM_LIBS=OFF -DCMAKE_PREFIX_PATH=C:/sdl-msvc/SDL2-%SDL2_VERSION%;C:/sdl-msvc/SDL2_mixer-%SDL2_MIXER_VERSION% ..

build_script:
  - cmake --build .

after_build:
  
  - if [%COMPILER%] == [msvc] cp debug/julius.exe .
  - if [%COMPILER%] == [msvc] cp C:\sdl-msvc\SDL2-%SDL2_VERSION%\lib\x86\SDL2.dll .
  - if [%COMPILER%] == [msvc] cp C:\sdl-msvc\SDL2_mixer-%SDL2_MIXER_VERSION%\lib\x86\SDL2_mixer.dll .
  - if [%COMPILER%] == [msvc] cp C:\sdl-msvc\SDL2_mixer-%SDL2_MIXER_VERSION%\lib\x86\libmpg123-0.dll .
  - if [%COMPILER%] == [mingw] cp C:\SDL2-%SDL2_VERSION%\i686-w64-mingw32\bin\SDL2.dll .
  - if [%COMPILER%] == [mingw] cp C:\SDL2_mixer-%SDL2_MIXER_VERSION%\i686-w64-mingw32\bin\SDL2_mixer.dll .
  - if [%COMPILER%] == [mingw] cp C:\SDL2_mixer-%SDL2_MIXER_VERSION%\i686-w64-mingw32\bin\libmpg123-0.dll .
  - if [%COMPILER%] == [mingw-w64] cp C:\SDL2-%SDL2_VERSION%\x86_64-w64-mingw32\bin\SDL2.dll .
  - if [%COMPILER%] == [mingw-w64] cp C:\SDL2_mixer-%SDL2_MIXER_VERSION%\x86_64-w64-mingw32\bin\SDL2_mixer.dll .
  - if [%COMPILER%] == [mingw-w64] cp C:\SDL2_mixer-%SDL2_MIXER_VERSION%\x86_64-w64-mingw32\bin\libmpg123-0.dll .
  - dir
  - set /P DEPLOY_VERSION=<C:\projects\julius\res\version.txt
  - if [%APPVEYOR_REPO_BRANCH:~0,8%] == [feature/] set DEPLOY_VERSION=%APPVEYOR_REPO_BRANCH:feature/=%-%DEPLOY_VERSION%
  - 7z a C:\projects\julius\julius-%DEPLOY_VERSION%-windows.zip julius.exe SDL2.dll SDL2_mixer.dll libmpg123-0.dll

cache:
  - SDL2-devel-%SDL2_VERSION%-mingw.tar.gz
  - SDL2_mixer-devel-%SDL2_MIXER_VERSION%-mingw.tar.gz
  - SDL2-devel-%SDL2_VERSION%-VC.zip
  - SDL2_mixer-devel-%SDL2_MIXER_VERSION%-VC.zip

artifacts:
  - path: build\julius.exe
    name: julius
  - path: julius-$(DEPLOY_VERSION)-windows.zip
    name: julius-dist
<<<<<<< HEAD:appveyor.yml
=======

before_deploy:
  - echo Deploying to %DEPLOY_VERSION%

deploy:
- provider: BinTray
  username: bvschaik
  api_key:
    secure: TJB/HaTTDyJCEht7jqfPiHvxR4kpQ9qeWpudvoXlSr/2IZUJ9HjOtagh8LeSWMth
  subject: bvschaik
  repo: julius-dev
  package: windows
  version: $(DEPLOY_VERSION)
  artifact: julius-dist
  publish: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: false
    CMAKE_BUILD_TYPE: Release
- provider: BinTray
  username: bvschaik
  api_key:
    secure: TJB/HaTTDyJCEht7jqfPiHvxR4kpQ9qeWpudvoXlSr/2IZUJ9HjOtagh8LeSWMth
  subject: bvschaik
  repo: julius
  package: windows
  version: $(DEPLOY_VERSION)
  artifact: julius-dist
  publish: true
  on:
    APPVEYOR_REPO_TAG: true
    CMAKE_BUILD_TYPE: Release
- provider: BinTray
  username: bvschaik
  api_key:
    secure: TJB/HaTTDyJCEht7jqfPiHvxR4kpQ9qeWpudvoXlSr/2IZUJ9HjOtagh8LeSWMth
  subject: bvschaik
  repo: julius-branches
  package: windows
  version: $(DEPLOY_VERSION)
  artifact: julius-dist
  publish: true
  on:
    branch: /feature\/.*/
    CMAKE_BUILD_TYPE: Release
>>>>>>> 2088c4915186da35a4e8a6c8308566be733b98c6:.appveyor.yml
